# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: github-insttoken
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    #darwin: Darwin
    linux: Linux
    #windows: Windows
    #386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: gbevan
    name: github-insttoken
  draft: false
  prerelease: false
  disable: false
